// <auto-generated />
using System;
using GolfClub.dbconnect;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GolfClub.Migrations
{
    [DbContext(typeof(AppDb))]
    partial class AppDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("GolfClub.Models.Bookings", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeeID")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookingId");

                    b.HasIndex("TeeID");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("GolfClub.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Handicap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MemberId");

                    b.ToTable("members");
                });

            modelBuilder.Entity("GolfClub.Models.TeeMembers", b =>
                {
                    b.Property<int>("TeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Player1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Player2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Player3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Player4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TeeID");

                    b.ToTable("tees");
                });

            modelBuilder.Entity("GolfClub.Models.Bookings", b =>
                {
                    b.HasOne("GolfClub.Models.TeeMembers", "tees")
                        .WithMany()
                        .HasForeignKey("TeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tees");
                });
#pragma warning restore 612, 618
        }
    }
}
